
all:
	gcc -I"C:\Program Files (x86)\AMD APP SDK\3.0\include" example.c -o example.exe -L"C:\Program Files (x86)\AMD APP SDK\3.0\lib\x86" -lOpenCL

ex2:
	gcc -I"C:\Program Files (x86)\AMD APP SDK\3.0\include" example2.c -o example2.exe -L"C:\Program Files (x86)\AMD APP SDK\3.0\lib\x86" -lOpenCL

mac:
	gcc main.c -o main -framework OpenCL

