

hash_map:
	gcc -I./../container/hash_map -I./../unittest hash_map_test.c ./../container/hash_map/hash_map.c
	./a.out
	rm a.out

hash_tree:
	gcc -I./../unittest -I./../container/hash_map -I./../container/hash_tree hash_tree_test.c ./../container/hash_map/hash_map.c ./../container/hash_tree/hash_tree.c
	./a.out
	rm a.out
